version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "androidx.appcompat:appcompat"
    open-pull-requests-limit: 20
